config/routes.rb
Rails.application.routes.draw do
  post 'twilio/sms'
  devise_for :users
  root to: "posts#index"
  get 'posts/new', to: 'posts#new', as: 'posts'
  post 'posts/new', to: 'posts#create', as: "new"
  get 'posts/:id', to: 'posts#show', as: "show"
  get "posts/:id/edit", to: 'posts#edit', as: "edit"
  patch 'posts/:id/edit', to: 'posts#update'
  delete 'posts/:id', to: 'posts#destroy', as: "delete"
  get "/about", to: "posts#about", as: "about"
  # post "notifications/notify", to: "notifications#notify"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# before_action @post = Post.find(params[:id])
    before_action :authenticate_user!
    skip_before_action :authenticate_user!, only: [:about]
    
    def index
        @posts = Post.all
    end
    
    def show
        @post = Post.find(params[:id].to_i)
        render 'posts/show'
    end

    def new
        @post = Post.new
        @post.body = 0
    end

    def create
        @post = Post.new(post_params)
        @post.save
        # message = "A post was just added."
        # TwilioTextMessenger.new(message).call
        redirect_to root_path
    end

    def edit
        @post = Post.find(params[:id].to_i)
        render "posts/edit"
    end

    def update
        @post = Post.find(params[:id].to_i)
        client = Twilio::REST::Client.new
        # raise params[:post][:body].inspect
        client.messages.create(from: "+17206053308", to: "+61468757015", body: "#{params[:post][:title]} now has #{params[:post][:body]} chocolates.")
        # puts params[:body] += 1
        # @post.body = @post.body.to_i + 1
        @post.update(post_params)
        redirect_to root_path
    end

    def about
        render "shared/about"
    end

    def destroy
        @post = Post.find(params[:id].to_i)
        @post.delete
        redirect_to root_path
    end

    private

    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController
  skip_before_action :verify_authenticity_token

  def sms
    body = helpers.parse_sms(params)
    response = Twilio::TwiML::MessagingResponse.new do |r|
      r.message body: body
    end
    render xml: response.to_s    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/twilio_helper.rb
module TwilioHelper
	def parse_sms(sms)

        body = sms[:Body]&.strip&.upcase
        from = sms[:From]

        case body

        when "HELLO"
            return "Hello world"

        else
            return "Sorry I didn't get that."
        end

end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackathonBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light container">
    <div class="row">
        <div class="col"><%= link_to 'Home', root_path, class: 'btn btn-info' %></div>
        <% if user_signed_in? %>
		<span class="nav-greeting"> <%= "Welcome back, #{current_user.email}" %> </span>
		<div class="col-auto"><%= link_to "Sign Out", destroy_user_session_path, method: "Delete", class: 'btn btn-info' %></div>
	<% else %>
		<div class="col-auto"><%= link_to "Sign In", new_user_session_path, class: 'btn btn-info' %></div>
		<div class="col-auto"><%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-info' %></div>
	<% end %>
    </div>
    <div class="col-auto"><%= link_to "About", about_path, class: 'btn btn-info' %></div>
  </nav>
    <div class="container">
    
    <% if not notice.nil? %>
     <p class="alert alert-success"><%= notice %></p>
    <% elsif not alert.nil? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="jumbotron"><h1>> git choc commit 🍫</h1>
<p class="lead">GitChoc Edit Page</p></div>



<%= form_with(model: @post, url: edit_path, method: "patch") do |form| %>
<table class="table">
  <tr><td>
  <%= form.label :title, "Name", class: "form-label" %></td>
  <td>
  <%= form.text_field :title, class: "form-control" %></td>
  </tr>
  
  <tr><td>
  <%= form.label :body, "Chocolates", class: "form-label" %></td>
  <td>
  <%= form.number_field :body, in: 1..100, step: 1, class: "form-control" %></td></tr>

  <tr><td>
  <button id="chocolateaddbutton" class="btn btn-success">Add 1 chocolate 😃</button>
  <button id="chocolateremovebutton" class="btn btn-danger">Remove 1 chocolate 😭</button>
  </td>
  
  <td>
  <%= form.submit "Update Chocolateer 🍫", class: "btn btn-primary" %>
  <%= link_to 'View Chocolateer 🍫', show_path(@post), class: "btn btn-warning" %>
  <%= link_to 'Back', root_path, class: "btn btn-danger" %></td></tr>
  </table>
<% end %>



<script>
  document.getElementById("chocolateaddbutton").addEventListener("click",(event) => {
    document.getElementById("post_body").value++;
    event.preventDefault();
    });

  document.getElementById("chocolateremovebutton").addEventListener("click",(event) => {
    document.getElementById("post_body").value--;
    event.preventDefault();
    });
</script>

app/views/posts/index.html.erb
<div class="jumbotron"><h1>> git choc log 🍫</h1>
<p class="lead">GitChoc Master List</p></div>

<table class="table">
<thead>
<th>Name</th>
<th>Chocolates</th>
<th colspan=3></th>
</thead>
<tbody>
<% @posts.each do |post| %>
<tr><td>
  <%= post.title %></td><td>
  <%= post.body %></td>


  <td><%= link_to 'View Chocolateer 🍫', show_path(post), class: 'btn btn-info' %></td>
        <td><%= link_to 'Update Chocolateer 🍫', edit_path(post), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Delete Chocolateer 🍫', delete_path(post), method: :delete, data: { confirm: 'Are you sure? There is NO TURNING BACK!' }, class: 'btn btn-danger' %></td>
        </tr>
<% end %>
</tbody>
</table>

<div class="col"><%= link_to 'New', new_path, class: 'btn btn-info' %></div>

app/views/posts/new.html.erb
<div class="jumbotron"><h1>> git choc init 🍫</h1>
<p class="lead">Create New Chocolateer 🍫</p></div>

<%= form_with(model: @post) do |form| %>
<table class="table">
  <tr>
  <td>
    <%= form.label :title, "Name", class: "form-label" %></td>
    <td>
    <%= form.text_field :title, class: "form-control" %></td>
  </tr>
  
  <tr>
  <td>
  <%= form.label :body, "Chocolates", class: "form-label" %></td>
  <td>
  <%= form.number_field :body, in: 1..100, step: 1, class: "form-control" %></td>
  </tr>

  <tr>
  <td></td>
  <td>
  <%= form.submit "New Chocolateer 🍫", class: "btn btn-primary" %></td></tr>
  </table>
<% end %>

app/views/posts/show.html.erb
<div class="jumbotron"><h1>> git choc checkout 🍫</h1>
<p class="lead">Your Personal Chocolate Count</p></div>

<table class="table">
<tr><td class="col-4 font-weight-bold">Name </td>
<td>
<%= @post.title %></td>
</tr><tr><td class="col-4 font-weight-bold">Number of Precious Chocolates 🤤 </td>
<td>
<%= @post.body %></td></tr>

<tr>
<td class="col-8">
<%= link_to 'Back', root_path, class: "btn btn-info" %>
<%= link_to 'Update Chocolateer 🍫', edit_path(@post), class: 'btn btn-warning' %>
<%= link_to 'Delete Chocolateer 🍫', delete_path(@post), method: :delete, data: { confirm: 'Are you sure? There is NO TURNING BACK!' }, class: 'btn btn-danger' %>
</td></tr>
</table>

app/views/shared/about.html.erb
<div class="jumbotron"><h1>About GitChoc</h1>
<p class="lead">Whenever a student answers a question correctly, they receive a chocolate.</p>
</div>
<%= image_tag "5976ev.jpg" %>
<p class="display-6">
Credits to: Lex</p>

app/views/twilio/sms.html.erb
<h1>Twilio#sms</h1>
<p>Find me in app/views/twilio/sms.html.erb</p>